"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import {
  generateChecklistFromFiles,
  assignTemplateToClient,
  getChecklistTemplateForEdit,
  type ClientChecklistSummary,
} from "@/lib/actions/checklist-templates";
import type { ChecklistTemplateInput } from "@/lib/validation/checklist";
import { TemplateForm } from "@/app/admin/checklist-templates/template-form";
import { Button } from "@/components/ui/button";
import { DataCard } from "@/components/ui/data-card";
import { ErrorBox } from "@/components/ui/error-box";
import { StatusBadge } from "@/components/ui/status-badge";
import { EmptyState } from "@/components/layout/page-shell";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";

type ClientChecklistSectionProps = {
  clientId: string;
  viewerIsAdmin: boolean;
  confirmedTemplate: ClientChecklistSummary | null;
  draftTemplate: ClientChecklistSummary | null;
};

/**
 * "Checklist de revisão" section. Two flows now live here (quick task
 * 260808-ci5):
 *
 * 1. The original admin-only manual "Gerar/Atualizar checklist com IA"
 *    button (P0 pivot 2026-08-04, item 1) — unchanged behavior, just now
 *    wrapped in `{viewerIsAdmin ? ... : null}` INSIDE this section instead
 *    of gating the whole section (client-detail-form.tsx renders this
 *    section unconditionally now).
 * 2. A NEW draft review/confirm affordance, visible to BOTH PM and Admin,
 *    rendered whenever `draftTemplate` is non-null — the automatic-
 *    on-upload draft generated by `generateChecklistDraftFromFiles`
 *    (client-files-section.tsx). Confirming via `TemplateForm
 *    mode="confirm-draft"` is the ONLY moment a draft becomes the client's
 *    active/gating checklist (`clients.checklist_template_id`).
 *
 * No local optimistic mirror of server state: every action that changes
 * server state calls `router.refresh()` instead (this project's
 * established convention against setState-from-props mirroring, see
 * chat-panel.tsx's activeClientId restructuring) — `confirmedTemplate`/
 * `draftTemplate` are rendered directly from props on every render.
 */
export function ClientChecklistSection({
  clientId,
  viewerIsAdmin,
  confirmedTemplate,
  draftTemplate,
}: ClientChecklistSectionProps) {
  const router = useRouter();

  // -- Admin-only manual generate/regenerate flow (unchanged) --
  const [proposal, setProposal] = useState<ChecklistTemplateInput | null>(
    null
  );
  const [dialogOpen, setDialogOpen] = useState(false);
  const [isGenerating, startGenerateTransition] = useTransition();
  const [generateError, setGenerateError] = useState<string | null>(null);

  function handleGenerate() {
    setGenerateError(null);
    startGenerateTransition(async () => {
      const result = await generateChecklistFromFiles(clientId);
      if ("error" in result) {
        setGenerateError(result.error);
        return;
      }
      setProposal(result.proposal);
      setDialogOpen(true);
    });
  }

  function handleSaved(templateId: string) {
    setDialogOpen(false);
    setProposal(null);

    // A client with no template yet: createTemplate only creates the row,
    // it never assigns it — that explicit second step happens here. A
    // client that already had one: updateTemplate edited it in place
    // (same id, echoed back by TemplateForm's onSuccess), so no new
    // assignment call is needed.
    if (!confirmedTemplate) {
      startGenerateTransition(async () => {
        const assignResult = await assignTemplateToClient({
          clientId,
          templateId,
        });
        if (assignResult.error) {
          toast.error(assignResult.error);
          return;
        }
        toast.success("Checklist gerado e atribuído a este cliente.");
        router.refresh();
      });
    } else {
      toast.success("Checklist atualizado.");
      router.refresh();
    }
  }

  // -- PM-or-Admin draft review/confirm flow (260808-ci5) — own, separate
  // Dialog/state so the two flows never collide. --
  const [reviewDialogOpen, setReviewDialogOpen] = useState(false);
  const [draftForEdit, setDraftForEdit] = useState<ChecklistTemplateInput | null>(
    null
  );
  const [isLoadingDraft, startLoadDraftTransition] = useTransition();
  const [loadDraftError, setLoadDraftError] = useState<string | null>(null);

  function handleReviewDraft() {
    if (!draftTemplate) return;
    setLoadDraftError(null);
    startLoadDraftTransition(async () => {
      const result = await getChecklistTemplateForEdit(draftTemplate.id);
      if (!result) {
        setLoadDraftError(
          "Não foi possível carregar o rascunho. Tente novamente."
        );
        return;
      }
      setDraftForEdit(result);
      setReviewDialogOpen(true);
    });
  }

  return (
    <DataCard
      title="Checklist de revisão"
      description="Regras que um card precisa cumprir antes de avançar de revisão interna — geradas pela IA a partir dos arquivos deste cliente, revisadas antes de confirmar."
    >
      <div className="flex flex-col gap-4">
        {confirmedTemplate ? (
          <p className="text-body">
            <span className="font-medium">{confirmedTemplate.name}</span> —{" "}
            {confirmedTemplate.itemCount}{" "}
            {confirmedTemplate.itemCount === 1 ? "item" : "itens"}
          </p>
        ) : !draftTemplate ? (
          <EmptyState
            title="Nenhum checklist atribuído"
            description={
              "Envie um arquivo do cliente para a IA gerar um rascunho automaticamente" +
              (viewerIsAdmin ? " ou gere manualmente abaixo." : ".")
            }
          />
        ) : null}

        {draftTemplate ? (
          <div className="flex flex-col gap-2 rounded-md border p-3">
            <StatusBadge tone="warning" className="w-fit">
              Rascunho gerado pela IA — aguardando revisão
            </StatusBadge>
            <p className="text-body">
              <span className="font-medium">{draftTemplate.name}</span> —{" "}
              {draftTemplate.itemCount}{" "}
              {draftTemplate.itemCount === 1 ? "item" : "itens"}
            </p>
            <Button
              type="button"
              variant="outline"
              onClick={handleReviewDraft}
              disabled={isLoadingDraft}
              className="w-fit"
            >
              {isLoadingDraft ? "Carregando..." : "Revisar e confirmar"}
            </Button>
            {loadDraftError ? <ErrorBox>{loadDraftError}</ErrorBox> : null}
          </div>
        ) : null}

        {viewerIsAdmin ? (
          <>
            <Button
              type="button"
              variant="outline"
              onClick={handleGenerate}
              disabled={isGenerating}
              className="w-fit"
            >
              {isGenerating ? "Gerando..." : "Gerar/Atualizar checklist com IA"}
            </Button>
            {generateError ? <ErrorBox>{generateError}</ErrorBox> : null}
          </>
        ) : null}
      </div>

      <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Revisar checklist gerado pela IA</DialogTitle>
          </DialogHeader>
          {proposal ? (
            <TemplateForm
              mode={confirmedTemplate ? "edit" : "create"}
              templateId={confirmedTemplate?.id}
              defaultValues={proposal}
              onSuccess={handleSaved}
            />
          ) : null}
        </DialogContent>
      </Dialog>

      <Dialog open={reviewDialogOpen} onOpenChange={setReviewDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Revisar e confirmar rascunho gerado pela IA</DialogTitle>
          </DialogHeader>
          {draftForEdit && draftTemplate ? (
            <TemplateForm
              mode="confirm-draft"
              templateId={draftTemplate.id}
              defaultValues={draftForEdit}
              onSuccess={() => {
                setReviewDialogOpen(false);
                router.refresh();
              }}
            />
          ) : null}
        </DialogContent>
      </Dialog>
    </DataCard>
  );
}
